# This file is adapted from https://github.com/RamblingCookieMonster/PSDiskPart/

# The MIT License (MIT)
# 
# Copyright (c) 2015 Warren F.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /update(d)? (README|CHANGELOG)/

os:
- Windows Server 2012 R2
- Unstable

install:
  - cinst pester --version 3.4.3

init:
  - git config --global core.autocrlf true
  
build: false

test_script:
# Test with native PS version
  - ps: . .\appveyor.pester.ps1
# Test with PS version 2
  - ps: if ( $PSVersionTable.PSVersion.Major -gt 2 ) { powershell.exe -version 2.0 -executionpolicy bypass -noprofile -file .\appveyor.pester.ps1 }
# Finalize pass - collect and upload results
  - ps: . .\appveyor.pester.ps1 -Finalize
